env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: 'module'
plugins:
- '@typescript-eslint'
extends:
- 'eslint:recommended'
- 'plugin:@typescript-eslint/recommended'
- 'prettier'
rules:
  indent: ['error', 2, { SwitchCase: 1 }]
  quotes: ['error', 'single']
  semi: ['warn', 'always']
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
